/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EnumTest;

public class App {
    Day day;

    public App(Day day) {
        this.day = day;
    }

    public void tellItLikeItIs() {
        switch (day) {
        case MONDAY:
            System.out.println("Mondays are bad.");
            break;

        case FRIDAY:
            System.out.println("Fridays are better.");
            break;

        case SATURDAY:
        case SUNDAY:
            System.out.println("Weekends are best.");
            break;

        default:
            System.out.println("Midweek days are so-so.");
            break;
        }
    }

    public static void main(String[] args) {
        App firstDay = new App(Day.MONDAY);
        firstDay.tellItLikeItIs();
        App thirdDay = new App(Day.WEDNESDAY);
        thirdDay.tellItLikeItIs();
        App fifthDay = new App(Day.FRIDAY);
        fifthDay.tellItLikeItIs();
        App sixthDay = new App(Day.SATURDAY);
        sixthDay.tellItLikeItIs();
        App seventhDay = new App(Day.SUNDAY);
        seventhDay.tellItLikeItIs();
    }
}
